kubeStateMetrics:
  enabled: true
  metricAllowlist:
    - kube_pod_labels
    - kube_pod_info
    - kube_deployment_spec_replicas
    - kube_deployment_status_replicas_ready
    - kube_deployment_status_replicas_available
  metricLabelsAllowlist:
    - "*"
  metricDenylist: []
