apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gha-monitoring-admin
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["secrets", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gha-monitoring-admin-rb
  namespace: monitoring
subjects:
- kind: Group
  name: github:ci
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: gha-monitoring-admin
  apiGroup: rbac.authorization.k8s.io
