# kubernetes/gha-rbac.yaml (APP NAMESPACE)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gh-actions-app-access
  namespace: prod
rules:
  # Deployments & scaling
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale", "replicasets"]
    verbs: ["get", "list", "watch", "update", "patch", "create"]

  # Services/Endpoints (apply + port-forward svc)
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  # Pods + logs/status (read)
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status"]
    verbs: ["get", "list", "watch"]

  # Exec & port-forward require "create" on subresources
  - apiGroups: [""]
    resources: ["pods/exec", "pods/portforward"]
    verbs: ["create"]

  # Optional: events
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gh-actions-app-access-rb
  namespace: prod
subjects:
  # keep your group if you use it
  - kind: Group
    name: gh-actions-deployer
    apiGroup: rbac.authorization.k8s.io
  # also bind the exact user the cluster sees ("gha")
  - kind: User
    name: gha
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: gh-actions-app-access
  apiGroup: rbac.authorization.k8s.io
