apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gha-prometheus-upgrade
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]

  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]

  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]

  - apiGroups: [""]
    resources: ["configmaps", "secrets", "services"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]

  
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["prometheuses", "servicemonitors", "alertmanagers", "prometheusrules"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]


  - apiGroups: ["apps"]
    resources: ["daemonsets", "deployments"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]

  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gha-prometheus-upgrade-rb
subjects:
  - kind: User
    name: gha
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: gha-prometheus-upgrade
  apiGroup: rbac.authorization.k8s.io
