name: AI-Powered CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-predict:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      run: python ml_model/train_model.py

    - name: Run prediction
      id: predict
      run: |
        PROBABILITY=$(python ml_model/predict_failure.py | grep "Failure Probability" | grep -o "[0-9]*\.[0-9]*")
        echo "Predicted Failure Probability: $PROBABILITY%"
        echo "fail_prob=$PROBABILITY" >> $GITHUB_OUTPUT

    - name: Decide deployment
      if: ${{ steps.predict.outputs.fail_prob < 60 }}
      run: echo "✅ Low risk - safe to deploy"

    - name: Block deployment
      if: ${{ steps.predict.outputs.fail_prob >= 60 }}
      run: echo "🛑 High failure risk - blocking deployment"
